/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ttdevs_jniutils_CipherUtils */

#ifndef _Included_com_ttdevs_jniutils_CipherUtils
#define _Included_com_ttdevs_jniutils_CipherUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ttdevs_jniutils_CipherUtils
 * Method:    base64Encode
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jstring JNICALL Java_com_ttdevs_jniutils_CipherUtils_base64Encode
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
